# Generated by Django 4.1.3 on 2022-12-13 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accelerator',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('bce94e49-f922-4882-bc21-198c4e6cf8e6'), primary_key=True, serialize=False)),
                ('acc_title', models.CharField(max_length=200)),
                ('acc_desc', models.CharField(max_length=500)),
                ('acc_url', models.URLField()),
                ('acc_img', models.ImageField(upload_to='')),
                ('acc_doc', models.URLField()),
                ('acc_video', models.URLField()),
                ('acc_how_it', models.CharField(max_length=500)),
                ('acc_no_of_days', models.IntegerField(default=0)),
                ('acc_logo', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
