# Generated by Django 4.1.3 on 2023-01-04 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accelerators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accelerator',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ec67409e-0392-4fb8-9768-b78feb3bad37'), primary_key=True, serialize=False),
        ),
    ]
