# Generated by Django 4.1.3 on 2023-01-04 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('7a96d08f-cba0-4fb3-bf91-a682d109fe0f'), primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
